### ISSUE TITLE
Cannot activate plugin

### ISSUE THREAD

**Issue by mvannas** [tkurki/polars-plugin#3]
Can't activate this plugin, I get the following errors if I try. Installation issue or missing file? 

    .properties['configuration'].properties['polars'].items.properties['name'].required should be array
    .properties['configuration'].properties['polars'].items.properties['trueWindSpeedUnit'].required  should be array
    .properties['configuration'].properties['polars'].items.properties['speedThroughWaterUnit'].required should be array
    .properties['configuration'].properties['polars'].items should be array
    .properties['configuration'].properties['polars'].items should match some schema in anyOf

**Comment by tkurki** [comment]
I have a hard understanding how the version that simply does not work ended up in Github. Sorry about it, now it should be in working condition.
